language: emacs

install:
  # Install emacs.
  - "sudo apt-get install emacs23-nox"

# run the tests
script:
  - curl -fsSkL https://raw.github.com/rejeep/carton/master/go | sh
  - bash ~/.carton/bin/carton
  - /bin/sh ./autogen.sh && EMACSLOADPATH=./elpa/test-simple*:$EMACSLOADPATH make check
